<a href="https://colab.research.google.com/github/MykolaRobot/ML_homework_1/blob/master/Data_prepr_batches_100_new.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [0]:
import pandas as pd
import time
from datetime import datetime
import numpy as np

In [2]:
filename='/content/gdrive/My Drive/ML_proz/data_source_cleaned.csv'
df=pd.read_csv(filename)
df.shape

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (1,5,14,15,16,17,18,24,38,48,50,51,53) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

(3507778, 57)

In [0]:
df['lots.guarantee_amount']=df[['lots.guarantee_amount','tenders.guarantee_amount']].apply(lambda raw:raw['tenders.guarantee_amount'] if
                                                                                          pd.isnull(raw['lots.guarantee_amount']) else raw['lots.guarantee_amount'],axis=1)

In [0]:
df['lots.guarantee_amount']=df[['lots.guarantee_amount']].apply(lambda raw: 0 if raw['lots.guarantee_amount']=='\\N' 
                                                               or str(raw['lots.guarantee_amount'])=='0.00' else raw['lots.guarantee_amount'],axis=1 )

In [3]:
cpv=pd.read_csv('/content/gdrive/My Drive/ML_proz/cpv (2).csv')
cpv.shape

(2687175, 3)

In [0]:
df=pd.merge(df,cpv,left_on='tenders.id',right_on='tender_id',how='left')

In [0]:
df['common_name']=df.apply(lambda raw: raw['tenderers_name'] if pd.notnull(raw['tenderers_name']) else (raw['awards.suppliers_identifier_legalName'] if raw['awards.suppliers_identifier_legalName']!='\\N' else raw['awards.suppliers_name']),axis=1)

In [0]:
class DataPreproccessing:
    def __init__(self, data_source, churn_interval=90, start_period=None, end_period=None,start_data_unique=None):
       
        data_source=data_source[pd.to_datetime(data_source['new_date'])>=start_period]
        data_source=data_source[pd.to_datetime(data_source['new_date'])<end_period]
        self.start_period=start_period
        self.end_period=end_period
        self.start_data_unique=start_data_unique
        self.last_day = pd.to_datetime('2018-11-29')
        self.divide_data = pd.to_datetime(self.end_period) - pd.DateOffset(days=churn_interval)
        print(self.divide_data)
        self.data_source = data_source[pd.to_datetime(data_source['new_date']) < self.divide_data]
        
        self.label_data = data_source[pd.to_datetime(data_source['new_date']) >= self.divide_data]
        # вибираємо унікальних постачальників
#         self.unique_id_data=self.data_source[(pd.to_datetime(self.data_source['new_date'])>=self.start_data_unique) & (pd.to_datetime(self.data_source['new_date'])<=self.divide_data)]
        self.unique_data=self.data_source[pd.to_datetime(self.data_source['new_date'])>=self.start_data_unique]
        self.unique_data=self.unique_data[pd.to_datetime(self.unique_data['new_date'])<self.divide_data]
        self.unique_id = list(self.unique_data['participants'].value_counts().index)
        # створюємо dataframe з колонкою унікальних постачальників і туди будемо додавати features
        self.feature_data = pd.DataFrame(self.unique_id, columns=['unique_id'])
        
    def print_dates(self):
        print('{0}:'.format((pd.to_datetime(self.divide_data)-pd.to_datetime(self.start_data_unique)).days))
        print('{0}:'.format((pd.to_datetime(self.end_period)-pd.to_datetime(self.start_data_unique)).days))
        print('Features: [{0}/{1})'.format(self.start_period,self.divide_data))
        print('Unique_id: [{0}/{1})'.format(self.start_data_unique,self.divide_data))
        print('Labeling: [{0}/{1}]'.format(self.divide_data,self.end_period))
    
    
    
    def cleaning(self):
        
        self.data_source['tenders.procuringEntity_address_postalCode']=self.data_source['tenders.procuringEntity_address_postalCode'].astype(str).str[:2]
        self.data_source['tenderers_address_postalCode']=self.data_source['tenderers_address_postalCode'].astype(str).str[:2]
        table_postal_code={'Київ':['01', '02', '03', '04', '05', '06'],
                  'Київська область':['07', '08', '09'],
                  'Житомирська область':['10', '11', '12', '13'],
                  'Черніговська область':['14', '15', '16', '17'],
                  'Черкаська область':['18', '19', '20'],
                  'Вінницька область':['21', '22', '23', '24'],
                  'Кіровоградська область':['25', '26', '27', '28'],
                  'Хмельницька область':['29', '30', '31', '32'],
                  'Рівненська область': ['33', '34', '35'],
                  'Полтавська область':['36', '37', '38', '39'],
                  'Сумська область':['40', '41', '42'],
                  'Волинська область':['43', '44', '45'],
                  'Тернопольська область':['46', '47', '48'],
                  'Дніпропетровська область':['49', '50', '51', '52', '53'],
                  'Миколаївська область':['54', '55', '56', '57'],
                  'Чернівецька область':['58', '59', '60'],
                  'Харьківська область':['61', '62', '63', '64'],
                  'Одеська область':['65', '66', '67', '68'],
                  'Запоріжська область':['69', '70', '71', '72'],
                  'Херсонська область':['73', '74', '75'],
                  'Івано-Франківська область':['76', '77', '78'],
                  'Львівська область':['79', '80', '81', '82'],
                  'Донецька область':['83', '84', '85', '86', '87'],
                  'Закарпатська область':['88', '89', '90'],
                  'Луганська область':['91', '92', '93', '94'],
                  'Автономна республіка Крим':['95', '96', '97', '98'],
                  'Севастопіль':['99']}
        regions=dict()
        for key,value in table_postal_code.items():
            for item in value:
              regions[item]=key
        def get_region(raw,regions):
            try:
              raw['region']=regions[raw['tenders.procuringEntity_address_postalCode']]
            except:  
              raw['region']=np.nan
            return raw
        self.data_source=self.data_source.apply(get_region,args=(regions,),axis=1)
        def get_region_supp(raw,regions):
            try:
              raw['region_supp']=regions[raw['tenderers_address_postalCode']]
            except:  
              raw['region_supp']=np.nan
            return raw
        self.data_source=self.data_source.apply(get_region_supp,args=(regions,),axis=1)
        print('regions updated')
        
    def split_into_batches(self, n=20000, filename=None):
        
        self.cleaning()
        feature_batches = list()
        n_iter = int(np.ceil(self.feature_data.shape[0] / n))
        for i in range(n_iter):
            start_time = time.time()
            print('Batch {0}-{1}:'.format(i * n, (i + 1) * n))
            unique_id = self.feature_data.iloc[i * n:(i + 1) * n]['unique_id'].values
            feature_df = pd.DataFrame(unique_id, columns=['unique_id'])
            feature_batches.append(feature_df)
            # part of data_source
            df_ = self.data_source.loc[self.data_source['participants'].isin(unique_id)]
            print('Unique_supp:{0}-{1}'.format(len(unique_id), df_.shape[0]))
            df_ = df_.sort_values(by='new_date')
            self.divide_data = str(self.divide_data)[:10]

            # features:
#             def get_most_common_name(raw,df):
#                 data=df[df['participants']==raw['unique_id']][['awards.suppliers_identifier_legalName','tenderers_name','awards.suppliers_name']]
#                 data['common_name']=data.apply(lambda raw: raw['tenderers_name'] if pd.notnull(raw['tenderers_name']) else (raw['awards.suppliers_identifier_legalName'] if raw['awards.suppliers_identifier_legalName']!='\\N' else raw['awards.suppliers_name']),axis=1)
#                 return raw
#             feature_batches[i] = feature_batches[i].apply(get_most_common_name, args=(df_[['participants','awards.suppliers_identifier_legalName','tenderers_name','awards.suppliers_name']],),axis=1)
#             # 0. First activity
            # 1. Last activity
            def get_last_activity(raw, data,eps=0.7):
                date=data[data['participants'] == raw['unique_id']]
                dates=date['new_date'].values
                # favourite host
                try:
                  if date['tenders.procuringEntity_identifier_id'].value_counts().iloc[0]/date.shape[0] >=eps:
                    raw['favourite_host']=1
                  else:
                    raw['favourite_host']=0
                  raw['count_unique_hosts']=date['tenders.procuringEntity_identifier_id'].value_counts().shape[0]
                except:
                  raw['favourite_host']=np.nan
                  raw['count_unique_hosts']=np.nan
                # name
                raw['common_name']=list(date['common_name'].value_counts().index)[0]
                # get cpv
                raw['cpv']=','.join([str(item) for item in set(date['cpv2'].values)])
                # average tender price
                raw['average_tender_price']=np.nanmean(date['lots.value_amount'])
                # count lots with guarantee amount
                raw['count_guarantee_lots']=np.count_nonzero(date['lots.guarantee_amount'])
                # unique_region
                raw['unique_regions']=len(set(date['region'].values))
                # get supp region
                try:
                  raw['supp_region']=list(date['region_supp'].value_counts().index)[0]
                except:
                  raw['supp_region']=np.nan
#                 raw['last_activity_date'] = dates[-1]
                try:
                    raw['first_activity_days'] = (
                        pd.to_datetime(self.divide_data) - pd.to_datetime(dates[0])).days
                    raw['last_activity_days'] = (
                        pd.to_datetime(self.divide_data) - pd.to_datetime(dates[-1])).days
                    if len(dates)!=1:
                      raw['average_activity']=(pd.to_datetime(dates[-1])-pd.to_datetime(dates[0])).days/(len(dates)-1)
                    else:
                      raw['average_activity']='?'
                except:
                    print('--------------')
                    raw['average_activity'] = '?'
                    
                return raw

            feature_batches[i] = feature_batches[i].apply(get_last_activity, args=(df_[['lots.guarantee_amount','lots.value_amount','common_name','cpv2','participants','new_date','tenders.procuringEntity_identifier_id','tenders.id','region','region_supp']],0.75,),
                                                          axis=1)
            feature_batches[i]['last_activity_days'] = feature_batches[i].apply(
                lambda x: 0 if x['last_activity_days'] < 0 else x['last_activity_days'], axis=1)
          
            # 3. Count lots
            freq = df_['participants'].value_counts()

            def count_lots(raw, frequency):
                raw['count_lots'] = frequency[raw['unique_id']]
                return raw

            feature_batches[i] = feature_batches[i].apply(count_lots, args=(freq,), axis=1)

            # 4. Win, lose
            frequency = df_[df_['winner'] == 1]['participants'].value_counts()
            def win_lose(raw, frequency):
                # use try bsc if index not in frequency 'win'=0
                try:
                    raw['win'] = frequency[raw['unique_id']]
                except:
                    raw['win'] = 0
                return raw

            feature_batches[i] = feature_batches[i].apply(win_lose, args=(
                frequency,), axis=1)
            feature_batches[i]['lose'] = feature_batches[i]['count_lots'] - feature_batches[i]['win']
          
#             5. Count win open

            frequency = df_.loc[(df_['winner'] == 1) & (df_['tenders.procurementMethod'] == 'open')][
                'participants'].value_counts()

            def count_win_open(raw, frequency):
                try:
                    raw['win_open'] = frequency[raw['unique_id']]
                except:
                    raw['win_open'] = 0
                return raw

            feature_batches[i] = feature_batches[i].apply(count_win_open, args=(
                frequency,), axis=1)
            feature_batches[i]['win_not_open'] = feature_batches[i]['win'] - feature_batches[i]['win_open']
          
#             6. Count lose open
            frequency = df_.loc[(df_['winner'] == 0) & (df_['tenders.procurementMethod'] == 'open')][
                'participants'].value_counts()

            def count_lose_open(raw, frequency):
                try:
                    raw['lose_open'] = frequency[raw['unique_id']]
                except:
                    raw['lose_open'] = 0
                return raw

            feature_batches[i] = feature_batches[i].apply(count_lose_open, args=(
                frequency,), axis=1)
#             feature_batches[i]['lose_not_open'] = feature_batches[i]['lose'] - feature_batches[i]['lose_open']
          
            # 7. Average economy
            data = df_[df_['winner'] == 1][
                ['participants', 'awards.value_amount', 'lots.value_amount']]
            data['economy_value'] = data['lots.value_amount'] - data['awards.value_amount']
            data['economy_percent'] = data['awards.value_amount'] / data['lots.value_amount']

            def get_economy(raw, data):
                d = data[data['participants'] == raw['unique_id']]
                raw['economy_value'] = np.nanmean(d['economy_value'])
                raw['average_winner_price']=np.nansum(d['awards.value_amount'])/d.shape[0]
                raw['economy_percent'] = np.nanmean(d['economy_percent'])
                return raw

            feature_batches[i] = feature_batches[i].apply(get_economy, args=(data,), axis=1)
#             8. Get label
            participants = list(self.label_data['participants'].value_counts().index)

            def get_y(raw, participants):
              if raw['unique_id'] in participants:
                  raw['y'] = 1
              else:
                  raw['y'] = 0
              return raw
#             9. Get favourite hosts
            feature_batches[i] = feature_batches[i].apply(get_y, args=(participants,), axis=1)
            # 10. Get unique region
        if filename:
            print(f'write to csv')
            feature_batches[i].to_csv(filename + '{0}'.format(i) + '.csv', index=False)

        # concat dataframes into one
        print('Concat')
        all_batches_df = pd.concat(feature_batches)
        self.feature_data = all_batches_df.copy()
        if filename:
            print('write to csv_all')
            all_batches_df.to_csv(filename + '_all.csv', index=False)
        print(" --- %s seconds ---" % (time.time() - start_time))
        all_batches_df['start_data_unique']=self.start_data_unique
        return all_batches_df
    def get_label(self):
        participants = list(self.label_data['participants'].value_counts().index)

        def get_y(raw, participants):
            if raw['unique_id'] in participants:
                raw['y'] = 1
            else:
                raw['y'] = 0
            return raw

        self.feature_data = self.feature_data.apply(get_y, args=(participants,), axis=1)

In [0]:
col=['winner','tenders.auctionPeriod_startDate','contracts.dateSigned',
     'awards.date','participants','date_from_id','contracts.value_amount','tenders.procurementMethod','contracts.status','awards.value_amount','tenders.id','tenders.procuringEntity_identifier_id','lots.value_amount']

In [0]:
start_period = '2016-09-10'
start_data_unique = ['2016-09-10', '2016-12-09', '2017-03-09', '2017-06-07', '2017-09-05', '2017-12-04']
end_period = ['2017-03-09', '2017-06-07', '2017-09-05', '2017-12-04', '2018-03-04', '2018-06-02']

In [43]:
df_list=list()
for i in range(len(end_period)):
  prepr = DataPreproccessing(df.iloc[:10000],start_period='2016-09-10',end_period=end_period[i],start_data_unique=start_data_unique[i],churn_interval=90)
  df_list.append(prepr.split_into_batches(n=1000))
  if i>0:
    print('i={0}'.format(i))
    print('Bad rows : {0}'.format(prepr.feature_data[prepr.feature_data['unique_id'].isin(z)].shape[0]))
  z=prepr.feature_data[prepr.feature_data['y']==0]['unique_id'].values
train=pd.concat(df_list)

2016-12-09 00:00:00
regions updated
Batch 0-1000:
Unique_supp:584-646

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:219: RuntimeWarning: Mean of empty slice
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:220: RuntimeWarning: invalid value encountered in double_scalars
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:221: RuntimeWarning: Mean of empty slice

Concat
 --- 9.862043380737305 seconds ---
2017-03-09 00:00:00
regions updated
Batch 0-1000:
Unique_supp:795-985
Concat
 --- 13.402435541152954 seconds ---
i=1
Bad rows : 0
2017-06-07 00:00:00
regions updated
Batch 0-1000:
Unique_supp:830-1057
Concat
 --- 14.151445388793945 seconds ---
i=2
Bad rows : 0
2017-09-05 00:00:00
regions updated
Batch 0-1000:
Unique_supp:899-1205
Concat
 --- 15.260045766830444 seconds ---
i=3
Bad rows : 0
2017-12-04 00:00:00
regions updated
Batch 0-1000:
Unique_supp:941-1340
Concat
 --- 16.08978271484375 seconds ---
i=4
Bad rows : 0
2018-03-04 00:00:00
regions updated
Batch 0-1000:
Unique_supp:1000-1691
Batch 1000-2000:
Unique_supp:223-295

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:126: RuntimeWarning: Mean of empty slice

Concat
 --- 3.8763954639434814 seconds ---
i=5
Bad rows : 0

In [51]:
train.head(20)

,unique_id,favourite_host,count_unique_hosts,common_name,cpv,average_tender_price,count_guarantee_lots,unique_regions,supp_region,first_activity_days,...,win,lose,win_open,win_not_open,lose_open,economy_value,average_winner_price,economy_percent,y,start_data_unique
0,39726851,0,7,ТОВ Пром Гарант Плюс,9,3.636400e+04,7,4,Дніпропетровська область,74,...,3,4,2,1,4,361.00,1.548833e+04,0.980654,1,2016-09-10
1,31816235,0,5,ТОВ Бадм,33,1.336320e+04,5,5,Дніпропетровська область,67,...,2,3,2,0,3,616.91,6.321090e+03,0.915751,1,2016-09-10
2,23291827,0,5,ПВКП Валлента,33,1.058200e+04,5,4,NaN,59,...,0,5,0,0,5,NaN,NaN,NaN,0,2016-09-10
3,23359034,0,4,"ПАТ ""ДТЕК ДНІПРООБЛЕНЕРГО""","9,51",1.549875e+05,4,1,NaN,39,...,4,0,0,4,0,0.00,1.549875e+05,1.000000,1,2016-09-10
4,38385636,0,4,"Общество с ограниченной ответственностью ""Элек...","44,31",2.674750e+04,4,4,NaN,81,...,1,3,1,0,3,0.00,6.000000e+03,1.000000,1,2016-09-10
5,40087705,0,3,ТОВ БІЛІМЕД,"33,18",1.249773e+06,3,3,Київ,71,...,1,2,1,0,2,1752000.00,1.850000e+06,0.513604,0,2016-09-10
6,39537943,0,3,ПП ГЛАВТОРГ,15,9.336000e+03,3,1,Донецька область,57,...,2,1,2,0,1,635.00,4.369000e+03,0.874750,1,2016-09-10
7,30297532,0,2,"Приватне підприємство ""Мале підприємство ""Сант...",45,3.219577e+05,3,1,Волинська область,43,...,3,0,1,2,0,12445.60,3.095121e+05,0.984345,0,2016-09-10
8,25394112,0,3,"Товариство з обмеженою відповідальністю ""Украї...",30,1.380000e+04,3,2,Київ,49,...,2,1,1,1,1,2650.05,1.504995e+04,0.850018,1,2016-09-10
9,32318370,0,3,"ТОВ ""ВП ""ПОЛІСАН""",44,5.549631e+04,3,3,Сумська область,79,...,1,2,1,0,2,915.68,3.520320e+03,0.793580,0,2016-09-10
10,38218086,0,3,"ТОВ ""Аметрін ФК""",33,3.094333e+04,3,3,Харьківська область,84,...,2,1,2,0,1,1409.29,2.354071e+04,0.944481,1,2016-09-10
11,2350917270,0,2,"ФОП ""Циганенко О.В""",33,9.600000e+03,2,2,Дніпропетровська область,59,...,0,2,0,0,2,NaN,NaN,NaN,0,2016-09-10
12,39197502,1,1,"ТОВ ""Тріалтрейд""",42,1.636000e+05,2,1,NaN,35,...,2,0,0,2,0,0.00,1.636000e+05,1.000000,0,2016-09-10
13,3257918908,0,2,Фізична особа підприємець Абакумова Наталія Ол...,"32,31",5.295000e+03,2,2,Київ,36,...,0,2,0,0,2,NaN,NaN,NaN,1,2016-09-10
14,2235023368,0,2,Фізична особа-підприємець Гентеш Ірина Григорівна,15,2.782000e+04,2,1,Дніпропетровська область,88,...,1,1,1,0,1,8587.20,1.205280e+04,0.583953,0,2016-09-10
15,40213527,1,1,"ТОВ ""ІНВЕСТИЦІЙНА ГРУПА УКРАЇНИ""",44,5.040639e+05,2,1,Харьківська область,84,...,1,1,0,1,1,0.00,6.186240e+04,1.000000,0,2016-09-10
16,40100448,0,2,"ТОВ ""ТОРГОВИЙ ДІМ ""НЄФТЕК""",9,5.460000e+04,2,1,Дніпропетровська область,53,...,2,0,2,0,0,4262.00,5.033800e+04,0.922841,0,2016-09-10
17,3210903800,0,2,ФОП Ситнік О.О.,"33,38",1.800000e+04,2,2,Дніпропетровська область,35,...,1,1,1,0,1,2100.00,9.900000e+03,0.825000,0,2016-09-10
18,32688148,0,2,Комунальне підприємство «Теплоенерго» Дніпропе...,9,6.408472e+05,2,2,NaN,42,...,2,0,0,2,0,-1500.00,6.423472e+05,1.001717,0,2016-09-10
19,2963509452,0,2,ФЛП Серб Павел Павлович,"48,30",4.600000e+05,2,2,Київська область,18,...,0,2,0,0,2,NaN,NaN,NaN,0,2016-09-10